### ISSUE TITLE
msg is not defined on hydra

### ISSUE THREAD

**Issue by Sacules** [diegodorado/tidal-hydra-tutorial#1]
Hola, al intentar los distintos métodos para conectar Hydra (versión web) con Tidal, me tira "msg is not defined". En el video veo que usás Atom, será parte del plugin?

**Comment by diegodorado** [comment]
SI, solo funciona en Atom. OSC no funciona en el browser.

**Comment by Sacules** [comment]
Ah bien, gracias! Estaría bueno aclararlo en el README :)

**Comment by diegodorado** [comment]
hecho!
